### ISSUE TITLE
C# feature sync: Extension Members

### ISSUE THREAD

**Issue by kyoyama-kazusa** [kyoyama-kazusa/Sudoku#542]
C# language design team wants to introduce a new feature called `extension`, a new type kind in C# type member.

## What is the feature?

This feature will allow you extending nearly everything. In C# 3, we have a feature called "Extension Methods", which can define a method that can be invoked like a normal instance:

```csharp
static void Method(this int variable)
    => Console.WriteLine(variable);
```

Then you can use this method, just like the type `int` contains this method:

```csharp
variable.Method();
```

Begin with C# 14, the feature expands the rule, to extend nearly all member kinds of a type:

* Extension Constructors
* Extension Fields
* Extension Properties
* Extension Indexers
* Extension Events
* Extension Methods
* Extension Operator Overloads
* Extension Cast Operator Overloads

Although constructors cannot be extended, this feature is still "good enough" for our coding environment.

I will sync the solution, using this feature to extend all types if worth.

```csharp
static class TypeExtension
{
    extension<T>(ref T obj) where T : allows ref struct
    {
        public TResult ReinterpretCast<TResult>() => Unsafe.As<T, TResult>(ref obj);
    }
}

float f = 42F;
int i = f.ReinterpretCast<int>();
```

## To-do list

- [ ] Extend built-in types
  - [x] Type `object`
    - [x] ~~`ReinterpretCast<>`: Cast the object to the other type without memory bits change, same as `Unsafe.As<,>`~~ (TBD)
    - [x] `operator true` and `operator false`: Determine whether a reference is not `null`.
  - [x] Type `string`
    - [x] `operator *(string, int)`: Repeats the string multiple times (return a `string[]`).
    - [x] `operator /(string, int)`: Split the string to multiple sub-strings of the specified length.
    - [x] `operator /(string, char)`: Split the string using the specified character separator.
    - [x] `operator /(string, string)`: Split the string using the specified string separator.
  - [x] Type `char`
    - [x] `operator *(char, int)`: Repeats the character multiple times.
  - [x] Types `byte`, `sbyte`, `ushort`, `short`, `uint`, `int`, `ulong`, `long`, `nint` and `nuint`
    - [x] ~~`this[int index]`: Gets the bit at the specified index~~ (language not supported)
    - [x] `GetEnumerator`: Iterates on each bit position.
    - [x] `operator true` and `operator false`: Check whether the value is not 0.
  - [ ] Enumeration types
    - [ ] `T.MinValue` and `T.MaxValue`: Defines the minimal and maximum value.
    - [ ] `T.All`: Defines all flags combined for an enumeration type marked `FlagsAttribute`.
    - [ ] `T.None`: Introduces the field that holds the default value.
    - [x] ~~`Reinterpret<TBase, TResult>`: Converts the enumeration field of type `TBase` to `TResult`, with whose name is same; equivalent to `Enum.Parse<TResult>(field.ToString())`.~~ (TBD)
- [x] Extend custom types
  - [x] Integer types `sbyte`, `byte`, `short`, `ushort`, `int`, `uint`, `long`, `ulong`, `nint` and `nuint`
    - [x] `Fallback`: Equals `sizeof(TInteger) << 3`, meaning the return value of `TrailingZeroCount(TInteger)` on value equals 0
  - [x] `IEnumerable` and `IEnumerable<T>`
    - [x] ~~`this[int index]`: Calls `ElementAt`~~ (language not supported)
    - [x] `Length`: Calls `Count()`.
    - [x] `IsEmpty`: Calls` Any()`.
    - [x] `Slice`: Slices the collection, also be used in slice operator `..`
    - [x] `operator +`: Concat enumerables.
    - [x] `operator *`: Calls `Aggregate`.
  - [x] `IGetSubsetMethod<TSelf, TSource>`:
    - [x] ~~`operator &(in TSelf, int)`: Calls `GetSubsetsExact`~~ (language not supported)
    - [x] ~~`operator |(in TSelf, int)`: Calls `GetSubsetsLower`~~ (language not supported)
  - [x] `List<T>`
    - [x] `operator +`: Calls `Add`.
    - [x] `operator -`: Calls `Remove`.
    - [x] ~~`implicit operator ReadOnlySpan<T>`: Implicit cast to `ReadOnlySpan<T>`~~ (language not supported)
    - [x] ~~`implicit operator Span<T>`: Implicit cast to `Span<T>`~~ (language not supported)
  - [x] `StringBuilder`
    - [x] ~~`operator >>`: Print formatted text from builder (language not supported)
    - [x] ~~`operator <<`: Add `item.ToString` into bulider (language not supported)
  - [x] `CancellationToken`
    - [x] `operator true`: Equivalent to `!ct.IsCancellationRequested`
    - [x] `operator false`: Equivalent to `ct.IsCancellationRequested`
  - [x] Exception types
    - [x] Helper methods
  - [x] Generic type
    - [x] ~~`explicit operator: in T -> T*`~~ (language not supported)
